# MakeCode Helper project
# Maintainer: Josiah

services:
  makecodehelper:
    build:
      context: .
      target: runner
    environment:
      VIRTUAL_PORT: 80 # tells the nginx proxy which port the app listens on
      VIRTUAL_HOST: mcai.dev.tk.sg # external hostname for the app
    networks:
      - devtksg
    expose:
      - "80"

networks:
  devtksg:
    external: true